// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiqtkhcggvkuqdbaoahh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppcXRraGNnZ3ZrdXFkYmFvYWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODMxNjEsImV4cCI6MjA1Nzc1OTE2MX0.Zn1JCq_oJB2ihiLrcY7g-V25H4HForDPLSIeLNgF7QA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);